services:
  postgres_db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: deliverease_db_user
      POSTGRES_PASSWORD: deliverease_db_pass
      POSTGRES_DB: deliverease_db
    volumes:
      - db_data:/var/lib/postgresql/data
  
  application:
    build:
      context: ./Application
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=deliverease_db
      - DB_USER=deliverease_db_user
      - DB_PASS=deliverease_db_pass
    depends_on:
      - postgres_db

  view:
    build:
      context: ./View
    depends_on:
      - application

networks:
  backend:
  web_app:

volumes:
  db_data: